#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor DP-4 -d 1 2 3 4 5
bspc monitor HDMI-0 -d 6 7 8
bspc monitor DP-3 -d 9 10

bspc config border_width 3
bspc config window_gap 0

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config focused_border_color "#2F5235"
bspc config active_border_color "#1D2033"
bspc config normal_border_color "#060A07"
bspc config presel_feedback_color "#2F5235"

$HOME/setbspwmcolors.sh

bspc wm --reorder-monitors DP-4 HDMI-0 DP-3
bspc config pointer_motion_interval 6ms
autorandr -l main

~/.scripts/randomwallpaper.sh
#~/.scripts/wormwal.fish
redshift -c .config/redshift/redshift.conf &
sxhkd &
dunst &
bspc desktop -f 1
picom --config .config/picom/picom.conf &
~/.config/polybar/launch.sh
syncthing-gtk &
steam -silent &
clipmenud &
arbtt-capture --sample-rate 1 &
kdeconnectd &
kdeconnect-indicator &
easyeffects --gapplication-service -l eq &
