#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

autorandr -l main

bspc monitor DP-4 -d 1 2 3 4 5
bspc monitor HDMI-0 -d 6 7 8
bspc monitor DP-3 -d 9 10

bspc config border_width 3
bspc config window_gap 5

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true

#bspc config focused_border_color "#2F5235"
#bspc config active_border_color "#1D2033"
#bspc config normal_border_color "#060A07"
#bspc config presel_feedback_color "#2F5235"

. "${HOME}/.cache/wal/colors.sh"
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config active_border_color "$color15"
bspc config presel_feedback_color "$color1"
bspc wm --reorder-monitors DP-4 HDMI-0 DP-3
bspc config pointer_motion_interval 6ms

wal -i ~/wallpapers/Simon/
redshift -c .config/redshift/redshift.conf &
sxhkd &
bspc desktop -f 1
syncthing --no-browser &
picom --config .config/picom/picom.conf &
~/.config/polybar/launch.sh
steam -silent &
clipmenud &
arbtt-capture --sample-rate 1 &

betterlockscreen -l
